// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user_fans.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class COMMONStatus;
@class USRFANSFanship;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - USRFANSUserFansRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface USRFANSUserFansRoot : GPBRootObject
@end

#pragma mark - USRFANSAddRequest

typedef GPB_ENUM(USRFANSAddRequest_FieldNumber) {
  USRFANSAddRequest_FieldNumber_FanId = 1,
};

@interface USRFANSAddRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fanId;

@end

#pragma mark - USRFANSFindParentRequest

typedef GPB_ENUM(USRFANSFindParentRequest_FieldNumber) {
  USRFANSFindParentRequest_FieldNumber_FanId = 1,
};

@interface USRFANSFindParentRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fanId;

@end

#pragma mark - USRFANSListChildRequest

typedef GPB_ENUM(USRFANSListChildRequest_FieldNumber) {
  USRFANSListChildRequest_FieldNumber_ParentId = 1,
  USRFANSListChildRequest_FieldNumber_From = 100,
  USRFANSListChildRequest_FieldNumber_Size = 101,
};

@interface USRFANSListChildRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *parentId;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - USRFANSFanshipResponse

typedef GPB_ENUM(USRFANSFanshipResponse_FieldNumber) {
  USRFANSFanshipResponse_FieldNumber_Fanship = 1,
  USRFANSFanshipResponse_FieldNumber_Status = 999,
};

@interface USRFANSFanshipResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, strong, null_resettable) USRFANSFanship *fanship;
/** Test to see if @c fanship has been set. */
@property(nonatomic, readwrite) BOOL hasFanship;

@end

#pragma mark - USRFANSFanship

typedef GPB_ENUM(USRFANSFanship_FieldNumber) {
  USRFANSFanship_FieldNumber_ParentId = 1,
  USRFANSFanship_FieldNumber_FanId = 2,
  USRFANSFanship_FieldNumber_Name = 3,
  USRFANSFanship_FieldNumber_Created = 4,
  USRFANSFanship_FieldNumber_ParentName = 11,
};

@interface USRFANSFanship : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *parentId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *parentName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fanId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t created;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
