// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/payment.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class COMMONStatus;
@class PAYMENTPayment;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PAYMENTChannel

typedef GPB_ENUM(PAYMENTChannel) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PAYMENTChannel_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PAYMENTChannel_Alipay = 0,
  PAYMENTChannel_Wxpay = 1,
  PAYMENTChannel_Yspay = 2,
};

GPBEnumDescriptor *PAYMENTChannel_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PAYMENTChannel_IsValidValue(int32_t value);

#pragma mark - Enum PAYMENTPayment_Status

typedef GPB_ENUM(PAYMENTPayment_Status) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PAYMENTPayment_Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PAYMENTPayment_Status_New = 0,
  PAYMENTPayment_Status_Inprogress = 50,
  PAYMENTPayment_Status_Failed = 51,
  PAYMENTPayment_Status_Ok = 52,
};

GPBEnumDescriptor *PAYMENTPayment_Status_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PAYMENTPayment_Status_IsValidValue(int32_t value);

#pragma mark - PAYMENTPaymentRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PAYMENTPaymentRoot : GPBRootObject
@end

#pragma mark - PAYMENTCreateRequest

typedef GPB_ENUM(PAYMENTCreateRequest_FieldNumber) {
  PAYMENTCreateRequest_FieldNumber_PayeeId = 12,
  PAYMENTCreateRequest_FieldNumber_PayeeStoreId = 13,
  PAYMENTCreateRequest_FieldNumber_PayeeWorkerId = 14,
  PAYMENTCreateRequest_FieldNumber_ShouldPay = 15,
  PAYMENTCreateRequest_FieldNumber_ActualPay = 16,
  PAYMENTCreateRequest_FieldNumber_PointsPay = 17,
};

@interface PAYMENTCreateRequest : GPBMessage

/**
 * only called by myself，即支付人是我
 * payerId
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeStoreId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeWorkerId;

/** 应付金额 = 实付金额 + 实付积分等价金额 */
@property(nonatomic, readwrite) int32_t shouldPay;

/** 实付金额 */
@property(nonatomic, readwrite) int32_t actualPay;

/** 实付积分代替金额 */
@property(nonatomic, readwrite) int32_t pointsPay;

@end

#pragma mark - PAYMENTGetRequest

typedef GPB_ENUM(PAYMENTGetRequest_FieldNumber) {
  PAYMENTGetRequest_FieldNumber_Uuid = 1,
};

@interface PAYMENTGetRequest : GPBMessage

/** 支付单编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - PAYMENTListRequest

typedef GPB_ENUM(PAYMENTListRequest_FieldNumber) {
  PAYMENTListRequest_FieldNumber_PayerId = 11,
  PAYMENTListRequest_FieldNumber_PayeeId = 12,
  PAYMENTListRequest_FieldNumber_PayeeStoreId = 13,
  PAYMENTListRequest_FieldNumber_From = 100,
  PAYMENTListRequest_FieldNumber_Size = 101,
};

@interface PAYMENTListRequest : GPBMessage

/** only called by manager */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payerId;

/** 收款人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeId;

/** 收款店铺 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeStoreId;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - PAYMENTListMyRequest

typedef GPB_ENUM(PAYMENTListMyRequest_FieldNumber) {
  PAYMENTListMyRequest_FieldNumber_IncludePayee = 1,
  PAYMENTListMyRequest_FieldNumber_IncludePayer = 2,
  PAYMENTListMyRequest_FieldNumber_From = 100,
  PAYMENTListMyRequest_FieldNumber_Size = 101,
};

@interface PAYMENTListMyRequest : GPBMessage

/** only called by myself */
@property(nonatomic, readwrite) BOOL includePayee;

@property(nonatomic, readwrite) BOOL includePayer;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - PAYMENTPaymentResponse

typedef GPB_ENUM(PAYMENTPaymentResponse_FieldNumber) {
  PAYMENTPaymentResponse_FieldNumber_Payment = 1,
  PAYMENTPaymentResponse_FieldNumber_Status = 999,
};

@interface PAYMENTPaymentResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, strong, null_resettable) PAYMENTPayment *payment;
/** Test to see if @c payment has been set. */
@property(nonatomic, readwrite) BOOL hasPayment;

@end

#pragma mark - PAYMENTPayment

typedef GPB_ENUM(PAYMENTPayment_FieldNumber) {
  PAYMENTPayment_FieldNumber_Uuid = 1,
  PAYMENTPayment_FieldNumber_PayerId = 11,
  PAYMENTPayment_FieldNumber_PayeeId = 12,
  PAYMENTPayment_FieldNumber_PayeeStoreId = 13,
  PAYMENTPayment_FieldNumber_PayeeWorkerId = 14,
  PAYMENTPayment_FieldNumber_ShouldPay = 15,
  PAYMENTPayment_FieldNumber_ActualPay = 16,
  PAYMENTPayment_FieldNumber_PointsPay = 17,
  PAYMENTPayment_FieldNumber_Points = 18,
  PAYMENTPayment_FieldNumber_Status = 19,
  PAYMENTPayment_FieldNumber_Channel = 26,
  PAYMENTPayment_FieldNumber_ChannelOrderId = 27,
  PAYMENTPayment_FieldNumber_Created = 40,
};

@interface PAYMENTPayment : GPBMessage

/** 支付单编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 支付人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payerId;

/** 收款人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeStoreId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeWorkerId;

/** create following info when return from Channel支付宝、微信等返回时 */
@property(nonatomic, readwrite) int32_t shouldPay;

/** 实付金额 */
@property(nonatomic, readwrite) int32_t actualPay;

/** 实付积分代替金额 */
@property(nonatomic, readwrite) int32_t pointsPay;

/** 返还积分 */
@property(nonatomic, readwrite) int32_t points;

@property(nonatomic, readwrite) PAYMENTPayment_Status status;

/** 支付通道如支付宝、微信、云闪付 */
@property(nonatomic, readwrite) PAYMENTChannel channel;

/** 预付单编号，可能由支付通道返回的或平台产生的 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelOrderId;

@property(nonatomic, readwrite) int64_t created;

@end

/**
 * Fetches the raw value of a @c PAYMENTPayment's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PAYMENTPayment_Status_RawValue(PAYMENTPayment *message);
/**
 * Sets the raw value of an @c PAYMENTPayment's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPAYMENTPayment_Status_RawValue(PAYMENTPayment *message, int32_t value);

/**
 * Fetches the raw value of a @c PAYMENTPayment's @c channel property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PAYMENTPayment_Channel_RawValue(PAYMENTPayment *message);
/**
 * Sets the raw value of an @c PAYMENTPayment's @c channel property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPAYMENTPayment_Channel_RawValue(PAYMENTPayment *message, int32_t value);

#pragma mark - PAYMENTUpdateWithAlipayBackRequest

typedef GPB_ENUM(PAYMENTUpdateWithAlipayBackRequest_FieldNumber) {
  PAYMENTUpdateWithAlipayBackRequest_FieldNumber_ChannelOrderId = 27,
};

@interface PAYMENTUpdateWithAlipayBackRequest : GPBMessage

/** 预付单编号，可能由支付通道返回的或平台产生的 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelOrderId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
