// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store/store_profile.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class COMMONLocation;
@class COMMONStatus;
@class STPRFListURL;
@class STPRFStoreProfile;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - STPRFStoreProfileRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface STPRFStoreProfileRoot : GPBRootObject
@end

#pragma mark - STPRFCreateRequest

typedef GPB_ENUM(STPRFCreateRequest_FieldNumber) {
  STPRFCreateRequest_FieldNumber_Name = 1,
  STPRFCreateRequest_FieldNumber_Location = 4,
  STPRFCreateRequest_FieldNumber_DistrictUuid = 9,
  STPRFCreateRequest_FieldNumber_DetailAddress = 10,
};

@interface STPRFCreateRequest : GPBMessage

/** 创建店铺需提供名称、地理位置、行政区编号、详细地址，其他内容通过单项修改完善 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) COMMONLocation *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *districtUuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailAddress;

@end

#pragma mark - STPRFCreateResponse

typedef GPB_ENUM(STPRFCreateResponse_FieldNumber) {
  STPRFCreateResponse_FieldNumber_Uuid = 1,
  STPRFCreateResponse_FieldNumber_Name = 2,
  STPRFCreateResponse_FieldNumber_OwnerId = 3,
  STPRFCreateResponse_FieldNumber_Status = 999,
};

@interface STPRFCreateResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerId;

@end

#pragma mark - STPRFUpdateRequest

typedef GPB_ENUM(STPRFUpdateRequest_FieldNumber) {
  STPRFUpdateRequest_FieldNumber_Uuid = 1,
  STPRFUpdateRequest_FieldNumber_Name = 2,
  STPRFUpdateRequest_FieldNumber_Logo = 3,
  STPRFUpdateRequest_FieldNumber_Location = 4,
  STPRFUpdateRequest_FieldNumber_Type = 6,
  STPRFUpdateRequest_FieldNumber_Desc = 7,
  STPRFUpdateRequest_FieldNumber_PointsRate = 8,
  STPRFUpdateRequest_FieldNumber_DistrictUuid = 9,
  STPRFUpdateRequest_FieldNumber_DetailAddress = 10,
  STPRFUpdateRequest_FieldNumber_Images = 11,
  STPRFUpdateRequest_FieldNumber_Active = 59,
};

typedef GPB_ENUM(STPRFUpdateRequest_Property_OneOfCase) {
  STPRFUpdateRequest_Property_OneOfCase_GPBUnsetOneOfCase = 0,
  STPRFUpdateRequest_Property_OneOfCase_Name = 2,
  STPRFUpdateRequest_Property_OneOfCase_Logo = 3,
  STPRFUpdateRequest_Property_OneOfCase_Location = 4,
  STPRFUpdateRequest_Property_OneOfCase_Type = 6,
  STPRFUpdateRequest_Property_OneOfCase_Desc = 7,
  STPRFUpdateRequest_Property_OneOfCase_PointsRate = 8,
  STPRFUpdateRequest_Property_OneOfCase_DistrictUuid = 9,
  STPRFUpdateRequest_Property_OneOfCase_DetailAddress = 10,
  STPRFUpdateRequest_Property_OneOfCase_Images = 11,
  STPRFUpdateRequest_Property_OneOfCase_Active = 59,
};

@interface STPRFUpdateRequest : GPBMessage

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 只支持单项修改 */
@property(nonatomic, readonly) STPRFUpdateRequest_Property_OneOfCase propertyOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *logo;

@property(nonatomic, readwrite, strong, null_resettable) COMMONLocation *location;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

/** 积分奖励率 */
@property(nonatomic, readwrite) int32_t pointsRate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *districtUuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailAddress;

@property(nonatomic, readwrite, strong, null_resettable) STPRFListURL *images;

@property(nonatomic, readwrite) BOOL active;

@end

/**
 * Clears whatever value was set for the oneof 'property'.
 **/
void STPRFUpdateRequest_ClearPropertyOneOfCase(STPRFUpdateRequest *message);

#pragma mark - STPRFListURL

typedef GPB_ENUM(STPRFListURL_FieldNumber) {
  STPRFListURL_FieldNumber_UrlsArray = 11,
};

@interface STPRFListURL : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *urlsArray;
/** The number of items in @c urlsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger urlsArray_Count;

@end

#pragma mark - STPRFUpdateResponse

typedef GPB_ENUM(STPRFUpdateResponse_FieldNumber) {
  STPRFUpdateResponse_FieldNumber_Uuid = 1,
  STPRFUpdateResponse_FieldNumber_Status = 999,
};

@interface STPRFUpdateResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - STPRFGetRequest

typedef GPB_ENUM(STPRFGetRequest_FieldNumber) {
  STPRFGetRequest_FieldNumber_Uuid = 1,
};

@interface STPRFGetRequest : GPBMessage

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - STPRFDeleteRequest

typedef GPB_ENUM(STPRFDeleteRequest_FieldNumber) {
  STPRFDeleteRequest_FieldNumber_Uuid = 1,
};

@interface STPRFDeleteRequest : GPBMessage

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - STPRFDeleteResponse

typedef GPB_ENUM(STPRFDeleteResponse_FieldNumber) {
  STPRFDeleteResponse_FieldNumber_Uuid = 1,
  STPRFDeleteResponse_FieldNumber_Status = 999,
};

@interface STPRFDeleteResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - STPRFListRequest

typedef GPB_ENUM(STPRFListRequest_FieldNumber) {
  STPRFListRequest_FieldNumber_Type = 3,
  STPRFListRequest_FieldNumber_From = 100,
  STPRFListRequest_FieldNumber_Size = 101,
};

@interface STPRFListRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - STPRFFindByNameRequest

typedef GPB_ENUM(STPRFFindByNameRequest_FieldNumber) {
  STPRFFindByNameRequest_FieldNumber_Name = 1,
};

@interface STPRFFindByNameRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - STPRFStoreProfileResponse

typedef GPB_ENUM(STPRFStoreProfileResponse_FieldNumber) {
  STPRFStoreProfileResponse_FieldNumber_StoreProfile = 1,
  STPRFStoreProfileResponse_FieldNumber_Status = 999,
};

@interface STPRFStoreProfileResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, strong, null_resettable) STPRFStoreProfile *storeProfile;
/** Test to see if @c storeProfile has been set. */
@property(nonatomic, readwrite) BOOL hasStoreProfile;

@end

#pragma mark - STPRFStoreProfile

typedef GPB_ENUM(STPRFStoreProfile_FieldNumber) {
  STPRFStoreProfile_FieldNumber_Uuid = 1,
  STPRFStoreProfile_FieldNumber_Name = 2,
  STPRFStoreProfile_FieldNumber_Logo = 3,
  STPRFStoreProfile_FieldNumber_Location = 4,
  STPRFStoreProfile_FieldNumber_Type = 6,
  STPRFStoreProfile_FieldNumber_Desc = 7,
  STPRFStoreProfile_FieldNumber_PointsRate = 8,
  STPRFStoreProfile_FieldNumber_DistrictUuid = 9,
  STPRFStoreProfile_FieldNumber_DetailAddress = 10,
  STPRFStoreProfile_FieldNumber_ImagesArray = 11,
  STPRFStoreProfile_FieldNumber_Active = 59,
  STPRFStoreProfile_FieldNumber_From = 100,
};

@interface STPRFStoreProfile : GPBMessage

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *logo;

@property(nonatomic, readwrite, strong, null_resettable) COMMONLocation *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

/** 积分奖励率 */
@property(nonatomic, readwrite) int32_t pointsRate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *districtUuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailAddress;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@property(nonatomic, readwrite) BOOL active;

@property(nonatomic, readwrite) int32_t from;

@end

#pragma mark - STPRFBanRequest

typedef GPB_ENUM(STPRFBanRequest_FieldNumber) {
  STPRFBanRequest_FieldNumber_Uuid = 1,
  STPRFBanRequest_FieldNumber_Active = 2,
};

@interface STPRFBanRequest : GPBMessage

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) BOOL active;

@end

#pragma mark - STPRFBanResponse

typedef GPB_ENUM(STPRFBanResponse_FieldNumber) {
  STPRFBanResponse_FieldNumber_Uuid = 1,
  STPRFBanResponse_FieldNumber_Active = 2,
  STPRFBanResponse_FieldNumber_Status = 999,
};

@interface STPRFBanResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

/** store uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) BOOL active;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
