// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accounting/accounting_tx.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ACCTXBalance;
@class ACCTXJournal;
@class ACCTXPaymentCreatedEvent;
@class ACCTXPosting;
@class ACCTXStoreVerifiedEvent;
@class ACCTXUserVerifiedEvent;
@class COMMONStatus;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ACCTXAccountingTxRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ACCTXAccountingTxRoot : GPBRootObject
@end

#pragma mark - ACCTXUpsertJournalRequest

typedef GPB_ENUM(ACCTXUpsertJournalRequest_FieldNumber) {
  ACCTXUpsertJournalRequest_FieldNumber_PaymentCreatedEvent = 1,
  ACCTXUpsertJournalRequest_FieldNumber_UserVerifiedEvent = 2,
  ACCTXUpsertJournalRequest_FieldNumber_StoreCreatedEvent = 3,
};

typedef GPB_ENUM(ACCTXUpsertJournalRequest_Event_OneOfCase) {
  ACCTXUpsertJournalRequest_Event_OneOfCase_GPBUnsetOneOfCase = 0,
  ACCTXUpsertJournalRequest_Event_OneOfCase_PaymentCreatedEvent = 1,
  ACCTXUpsertJournalRequest_Event_OneOfCase_UserVerifiedEvent = 2,
  ACCTXUpsertJournalRequest_Event_OneOfCase_StoreCreatedEvent = 3,
};

@interface ACCTXUpsertJournalRequest : GPBMessage

@property(nonatomic, readonly) ACCTXUpsertJournalRequest_Event_OneOfCase eventOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXPaymentCreatedEvent *paymentCreatedEvent;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXUserVerifiedEvent *userVerifiedEvent;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXStoreVerifiedEvent *storeCreatedEvent;

@end

/**
 * Clears whatever value was set for the oneof 'event'.
 **/
void ACCTXUpsertJournalRequest_ClearEventOneOfCase(ACCTXUpsertJournalRequest *message);

#pragma mark - ACCTXListJournalRequest

typedef GPB_ENUM(ACCTXListJournalRequest_FieldNumber) {
  ACCTXListJournalRequest_FieldNumber_From = 100,
  ACCTXListJournalRequest_FieldNumber_Size = 101,
};

@interface ACCTXListJournalRequest : GPBMessage

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - ACCTXGetJournalRequest

typedef GPB_ENUM(ACCTXGetJournalRequest_FieldNumber) {
  ACCTXGetJournalRequest_FieldNumber_Uuid = 1,
};

@interface ACCTXGetJournalRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - ACCTXJournalResponse

typedef GPB_ENUM(ACCTXJournalResponse_FieldNumber) {
  ACCTXJournalResponse_FieldNumber_Journal = 1,
  ACCTXJournalResponse_FieldNumber_Status = 999,
};

@interface ACCTXJournalResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXJournal *journal;
/** Test to see if @c journal has been set. */
@property(nonatomic, readwrite) BOOL hasJournal;

@end

#pragma mark - ACCTXJournal

typedef GPB_ENUM(ACCTXJournal_FieldNumber) {
  ACCTXJournal_FieldNumber_PaymentCreatedEvent = 1,
  ACCTXJournal_FieldNumber_UserVerifiedEvent = 2,
  ACCTXJournal_FieldNumber_StoreVerifiedEvent = 3,
  ACCTXJournal_FieldNumber_Uuid = 11,
  ACCTXJournal_FieldNumber_Created = 12,
  ACCTXJournal_FieldNumber_PostingsArray = 33,
  ACCTXJournal_FieldNumber_PostingsCreated = 34,
};

typedef GPB_ENUM(ACCTXJournal_Event_OneOfCase) {
  ACCTXJournal_Event_OneOfCase_GPBUnsetOneOfCase = 0,
  ACCTXJournal_Event_OneOfCase_PaymentCreatedEvent = 1,
  ACCTXJournal_Event_OneOfCase_UserVerifiedEvent = 2,
  ACCTXJournal_Event_OneOfCase_StoreVerifiedEvent = 3,
};

@interface ACCTXJournal : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite) int64_t created;

@property(nonatomic, readonly) ACCTXJournal_Event_OneOfCase eventOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXPaymentCreatedEvent *paymentCreatedEvent;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXUserVerifiedEvent *userVerifiedEvent;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXStoreVerifiedEvent *storeVerifiedEvent;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ACCTXPosting*> *postingsArray;
/** The number of items in @c postingsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postingsArray_Count;

@property(nonatomic, readwrite) int64_t postingsCreated;

@end

/**
 * Clears whatever value was set for the oneof 'event'.
 **/
void ACCTXJournal_ClearEventOneOfCase(ACCTXJournal *message);

#pragma mark - ACCTXPaymentCreatedEvent

typedef GPB_ENUM(ACCTXPaymentCreatedEvent_FieldNumber) {
  ACCTXPaymentCreatedEvent_FieldNumber_Uuid = 1,
  ACCTXPaymentCreatedEvent_FieldNumber_PayerId = 11,
  ACCTXPaymentCreatedEvent_FieldNumber_PayeeId = 12,
  ACCTXPaymentCreatedEvent_FieldNumber_PayeeStoreId = 13,
  ACCTXPaymentCreatedEvent_FieldNumber_PayeeWorkerId = 14,
  ACCTXPaymentCreatedEvent_FieldNumber_Shouldpay = 15,
  ACCTXPaymentCreatedEvent_FieldNumber_Actualpay = 16,
  ACCTXPaymentCreatedEvent_FieldNumber_Bonuspay = 17,
  ACCTXPaymentCreatedEvent_FieldNumber_Channel = 26,
  ACCTXPaymentCreatedEvent_FieldNumber_Created = 27,
};

@interface ACCTXPaymentCreatedEvent : GPBMessage

/** uuid unique */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 支付人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payerId;

/** 收款人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeStoreId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payeeWorkerId;

/** 应付金额 = 实付金额 + 实付积分等价金额 */
@property(nonatomic, readwrite) int32_t shouldpay;

/** 实付金额 */
@property(nonatomic, readwrite) int32_t actualpay;

/** 实付积分代替金额 */
@property(nonatomic, readwrite) int32_t bonuspay;

/** 支付通道如支付宝、微信、云闪付 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

@property(nonatomic, readwrite) int64_t created;

@end

#pragma mark - ACCTXUserVerifiedEvent

typedef GPB_ENUM(ACCTXUserVerifiedEvent_FieldNumber) {
  ACCTXUserVerifiedEvent_FieldNumber_UserId = 11,
  ACCTXUserVerifiedEvent_FieldNumber_IntroducerId = 12,
  ACCTXUserVerifiedEvent_FieldNumber_Created = 14,
};

@interface ACCTXUserVerifiedEvent : GPBMessage

/** userId+introducerId unique */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *introducerId;

@property(nonatomic, readwrite) int64_t created;

@end

#pragma mark - ACCTXStoreVerifiedEvent

typedef GPB_ENUM(ACCTXStoreVerifiedEvent_FieldNumber) {
  ACCTXStoreVerifiedEvent_FieldNumber_StoreId = 11,
  ACCTXStoreVerifiedEvent_FieldNumber_IntroducerId = 12,
  ACCTXStoreVerifiedEvent_FieldNumber_StoreOwnerId = 13,
  ACCTXStoreVerifiedEvent_FieldNumber_Created = 14,
};

@interface ACCTXStoreVerifiedEvent : GPBMessage

/** storeId+introducerId unique */
@property(nonatomic, readwrite, copy, null_resettable) NSString *storeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *introducerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *storeOwnerId;

@property(nonatomic, readwrite) int64_t created;

@end

#pragma mark - ACCTXListPostingRequest

typedef GPB_ENUM(ACCTXListPostingRequest_FieldNumber) {
  ACCTXListPostingRequest_FieldNumber_UserId = 11,
  ACCTXListPostingRequest_FieldNumber_AccountId = 12,
  ACCTXListPostingRequest_FieldNumber_JournalId = 13,
  ACCTXListPostingRequest_FieldNumber_From = 100,
  ACCTXListPostingRequest_FieldNumber_Size = 101,
};

@interface ACCTXListPostingRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** accountId+journalId unique */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;

/** optional */
@property(nonatomic, readwrite, copy, null_resettable) NSString *journalId;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - ACCTXGetPostingRequest

typedef GPB_ENUM(ACCTXGetPostingRequest_FieldNumber) {
  ACCTXGetPostingRequest_FieldNumber_Uuid = 1,
};

@interface ACCTXGetPostingRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - ACCTXPostingResponse

typedef GPB_ENUM(ACCTXPostingResponse_FieldNumber) {
  ACCTXPostingResponse_FieldNumber_Posting = 1,
  ACCTXPostingResponse_FieldNumber_Status = 999,
};

@interface ACCTXPostingResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXPosting *posting;
/** Test to see if @c posting has been set. */
@property(nonatomic, readwrite) BOOL hasPosting;

@end

#pragma mark - ACCTXPosting

typedef GPB_ENUM(ACCTXPosting_FieldNumber) {
  ACCTXPosting_FieldNumber_Uuid = 1,
  ACCTXPosting_FieldNumber_UserId = 11,
  ACCTXPosting_FieldNumber_AccountId = 12,
  ACCTXPosting_FieldNumber_JournalId = 13,
  ACCTXPosting_FieldNumber_Amount = 14,
  ACCTXPosting_FieldNumber_Created = 15,
  ACCTXPosting_FieldNumber_Comment = 16,
};

@interface ACCTXPosting : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** accountId+journalId unique */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *journalId;

@property(nonatomic, readwrite) int32_t amount;

@property(nonatomic, readwrite) int64_t created;

@property(nonatomic, readwrite, copy, null_resettable) NSString *comment;

@end

#pragma mark - ACCTXListBalanceRequest

typedef GPB_ENUM(ACCTXListBalanceRequest_FieldNumber) {
  ACCTXListBalanceRequest_FieldNumber_AccountUuid = 1,
  ACCTXListBalanceRequest_FieldNumber_From = 100,
  ACCTXListBalanceRequest_FieldNumber_Size = 101,
};

@interface ACCTXListBalanceRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountUuid;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - ACCTXBalanceResponse

typedef GPB_ENUM(ACCTXBalanceResponse_FieldNumber) {
  ACCTXBalanceResponse_FieldNumber_Balance = 1,
  ACCTXBalanceResponse_FieldNumber_Status = 999,
};

@interface ACCTXBalanceResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, strong, null_resettable) ACCTXBalance *balance;
/** Test to see if @c balance has been set. */
@property(nonatomic, readwrite) BOOL hasBalance;

@end

#pragma mark - ACCTXBalance

typedef GPB_ENUM(ACCTXBalance_FieldNumber) {
  ACCTXBalance_FieldNumber_AccountUuid = 1,
  ACCTXBalance_FieldNumber_PreviousBalance = 15,
  ACCTXBalance_FieldNumber_PreviousDate = 16,
  ACCTXBalance_FieldNumber_CurrentChanges = 17,
  ACCTXBalance_FieldNumber_CurrentDate = 18,
  ACCTXBalance_FieldNumber_CurrentBalance = 19,
};

@interface ACCTXBalance : GPBMessage

/** | 账户编号UUID      | 前期余额  | 前期日期  | 当期变化 | 当期日期  | 当期余额 |  CRC    | */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accountUuid;

@property(nonatomic, readwrite) int32_t previousBalance;

@property(nonatomic, readwrite) int64_t previousDate;

@property(nonatomic, readwrite) int32_t currentChanges;

@property(nonatomic, readwrite) int64_t currentDate;

@property(nonatomic, readwrite) int32_t currentBalance;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
