// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store/store_owner.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class COMMONStatus;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - STOWNStoreOwnerRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface STOWNStoreOwnerRoot : GPBRootObject
@end

#pragma mark - STOWNTransferRequest

typedef GPB_ENUM(STOWNTransferRequest_FieldNumber) {
  STOWNTransferRequest_FieldNumber_StoreId = 1,
  STOWNTransferRequest_FieldNumber_UserId = 3,
};

@interface STOWNTransferRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *storeId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - STOWNListByOwnerRequest

typedef GPB_ENUM(STOWNListByOwnerRequest_FieldNumber) {
  STOWNListByOwnerRequest_FieldNumber_OwnerId = 3,
  STOWNListByOwnerRequest_FieldNumber_From = 100,
  STOWNListByOwnerRequest_FieldNumber_Size = 101,
};

@interface STOWNListByOwnerRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerId;

@property(nonatomic, readwrite) int32_t from;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - STOWNOwnershipResponse

typedef GPB_ENUM(STOWNOwnershipResponse_FieldNumber) {
  STOWNOwnershipResponse_FieldNumber_OwnerId = 1,
  STOWNOwnershipResponse_FieldNumber_StoreId = 5,
  STOWNOwnershipResponse_FieldNumber_Active = 7,
  STOWNOwnershipResponse_FieldNumber_StartTime = 9,
  STOWNOwnershipResponse_FieldNumber_EndTime = 10,
  STOWNOwnershipResponse_FieldNumber_From = 100,
  STOWNOwnershipResponse_FieldNumber_Status = 999,
};

@interface STOWNOwnershipResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) COMMONStatus *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *storeId;

@property(nonatomic, readwrite) BOOL active;

@property(nonatomic, readwrite) int64_t startTime;

@property(nonatomic, readwrite) int64_t endTime;

@property(nonatomic, readwrite) int32_t from;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
